version: 2
jobs:
  "python-35":
    working_directory: ~/featuretools_categorical_encoding
    docker:
        - image: circleci/python:3.5
    steps:
      - checkout
      - run: |
          virtualenv venv_35
          source venv_35/bin/activate
          make installdeps
      - run: |
          source venv_35/bin/activate
          make lint
      - run: |
          source venv_35/bin/activate
          coverage erase
          make test
          codecov

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "python-35"
